### ISSUE TITLE
yarn dev err : exec: "pnpm": executable file not found in $PATH

### ISSUE THREAD

**Issue by onionwithhoney** [quassum/SVG-to-SwiftUI#27]
environment：Mac M1 ,nodejs v19.5.0
git success,
cd success,
yarn success,
yarn dev , err:

{
yarn run v1.22.19
$ turbo run dev --parallel
• Packages in scope: svg-to-swiftui-core, svg-to-swiftui-webapp, tsconfig
• Running dev in 3 packages
• Remote caching disabled
svg-to-swiftui-webapp:dev: cache bypass, force executing ed5afce2520048ec
svg-to-swiftui-webapp:dev: ERROR: command finished with error: exec: "pnpm": executable file not found in $PATH
exec: "pnpm": executable file not found in $PATH

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    168ms 

 ERROR  run failed: command  exited (1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

}

**Comment by bring-shrubbery** [comment]
> Just a note: please use code blocks for code. More [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

@onionwithhoney This repository uses `pnpm`, not `yarn`. It's more similar to `npm` than `yarn`, but does some things better than both. You can install it by running `npm i -g pnpm` or `yarn global add pnpm`.

**Comment by onionwithhoney** [comment]
Thanks! I run 【yarn global add pnpm】,now I can run this object on localhost:3000  .
I had compare the result between the local and your online result，It is exactly the same code result。

**Comment by bring-shrubbery** [comment]
> Thanks! I run 【yarn global add pnpm】,now I can run this object on localhost:3000  .
> 
> I had compare the result between the local and your online result，It is exactly the same code result。
> 
> 

Yes it is. The online version is hosted on GitHub Pages, but otherwise it's exactly the same.
