### ISSUE TITLE
Link to sf guide is dead

### ISSUE THREAD

**Issue by eonist** [quassum/SVG-to-SwiftUI#9]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bring-shrubbery** [comment]
@eonist Please remove the description if you're not using it :) Will update the link later though :)

**Comment by eonist** [comment]
was on my mobile. sorry

**Comment by bring-shrubbery** [comment]
@eonist Could you check the links again, all links seem to work for me now :)

**Comment by eonist** [comment]
Must have been on their end. all links work now.
